name: Frontend CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Login to GHCR
        if: github.event_name == 'push'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io \
            -u ${{ github.actor }} \
            --password-stdin

      - name: Build Docker Image
        if: github.event_name == 'push'
        run: |
          docker build \
            -t ghcr.io/neueda-learning/bnd-ui:latest .

      - name: Push Docker Image
        if: github.event_name == 'push'
        run: |
          docker push ghcr.io/neueda-learning/bnd-ui:latest

      - name: Trigger Jenkins CD
        if: github.event_name == 'push'
        run: |
          curl -X POST \
            "${{ secrets.JENKINS_URL }}/buildByToken/build?job=bnd-ui-deploy-job&token=${{ secrets.JENKINS_TOKEN }}"